@api=http://localhost:3001/api/v1/register
@apiUser=http://localhost:3001/api/v1/users
@apiAuth=http://localhost:3001/api/v1/users/auth
@apiInfo=http://localhost:3001/api/v1/info/options
@apiInfo2=http://localhost:3001/api/v1/info/name


### Post
POST {{api}}
Content-Type: application/json

{
    "Nombre1": "Andrea",
    "Nombre2": "Melissa",
    "Apellido1": "Orozco",
    "Apellido2": "Ruiz",
    "Genero": "F",
    "Fecha_Nac": "2004-04-12",
    "Users": "melissaruiz@gmail.com",
    "Contraseña": "meli2412"
}

### getcliente
GET {{api}}
Content-Type: application/json

### getUser
GET {{apiUser}}
Content-Type: application/json

### getInfo
GET {{apiInfo}}
Content-Type: application/json

### getName
GET {{apiInfo2}}
Content-Type: application/json

### authUser
POST {{apiAuth}}
Content-Type: application/json

{
    "Users": "amaru@gmail.com",
    "Contraseña": "amaruernesto"
}